<Layout>:
    cols:1
    qrTextInput: qrcode
    MDTextField:
        id: qrcode
        hint_text: "QR Code"
        focus: True
        helper_text: "Enter Shipment QR"
        helper_text_mode: "on_focus"
        icon_right: "qrcode-scan"
        icon_right_color: app.theme_cls.primary_color
        pos_hint:{'center_x': 0.5, 'center_y': 0.9}
        size_hint_x:None
        width:300
        on_text_validate: root.check()